/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "uart.h"
#include "adc.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    UartInit(115200);   // UART2 init on PA2 (TX), PA3 (RX)
    AdcInit();          // ADC init on PA0 (MQ135 input)

    char msg[50];
    uint16_t adc_value;

    while(1)
    {
        adc_value = AdcRead();  // read MQ135 voltage via ADC

        sprintf(msg, "MQ135 ADC = %d\r\n", adc_value);
        UartPuts(msg);          // print to serial monitor

        for(volatile int i = 0; i < 500000; i++);  // small delay
    }
}

