/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */

/*

PA2 (USART2_TX)   ----->     RX
PA3 (USART2_RX)   <-----     TX
GND               --------    GND
3.3V (optional)   ----->     VCC (only if TTL needs power)


VCC        -------->   3.3V
GND        -------->   GND
SCL        -------->   PB6  (I2C1_SCL)
SDA        -------->   PB7  (I2C1_SDA)
ADDR       -------->   GND  (Sensor address = 0x23)

*/
#include "stm32f4xx.h"
#include "i2c.h"
#include "uart.h"
#include "bh1750.h"
#include "led.h"       // Include the new LED header
#include <stdio.h>
#include"timer.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// Define the Lux threshold for turning LEDs ON
#define GREENHOUSE_LUX_THRESHOLD 15000U // 15,000 lux (Vegetative growth threshold)

char msg[80];

int main(void)
{
	TimerPwmInit();
    UartInit(115200);    // Initialize UART2 @ 115200 baud
    UartPuts("Greenhouse Controller Active.\r\n");
    I2CInit();           // Initialize I2C1 (PB6=SCL, PB7=SDA)
    BH1750_Init();       // Power ON - Reset - H-Resolution Mode
    //LedInit();           // Initialize LEDs on GPIOD Pins 12-15

    //
//    while(1)
//    {
//        uint16_t lux = BH1750_ReadLux();   // Read light intensity in lux
//
//        // Check against the defined threshold
//        /*
//        if (lux < GREENHOUSE_LUX_THRESHOLD) {
//            LedsOn(); // Turn on all 4 supplemental LEDs
//            sprintf(msg, "Intensity = %u lux. ACTION: LEDs ON.\r\n", lux);
//        } else {
//            LedsOff(); // Turn off supplemental LEDs
//            sprintf(msg, "Intensity = %u lux. ACTION: LEDs OFF (sufficient sunlight).\r\n", lux);
//        }
//        */
//
//
//        UartPuts(msg);                      // Send status to UART
//        DelayMs(1000);                      // Check every 1 second
//    }
     while (1)
     {
        uint16_t lux = BH1750_ReadLux();
        uint8_t duty;

        if (lux < 2000)       duty = 90;
        else if (lux < 5000)  duty = 70;
        else if (lux < 10000) duty = 40;
        else if (lux < 15000) duty = 20;
        else                  duty = 0;

        TIM8->CCR1 = duty;

        sprintf(msg,
                "Lux=%u | PWM=%u%% | Grow Light %s\r\n",
                lux,
                duty,
                (duty > 0) ? "ON" : "OFF");

        UartPuts(msg);
        DelayMs(1000);
    }



}

