/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "uart.h"
#include "i2c.h"
#include "i2c1.h"
#include "bh1750.h"
#include "timer.h"
#include "adc.h"
#include "bme280.h"

#define LOOP_DELAY_MS 5000

int main(void)
{
    uint16_t light_intensity;
    uint8_t led_status;

    uint8_t soil_moisture;
    uint8_t pump_status;

    uint16_t mq135_adc;

    float temperature, humidity;
    uint8_t fan_status;

    char uart_buf[200];

    SystemInit();
    UartInit(115200);
    DelayMs(1000);

    AdcInit();
    I2CInit();      // BH1750
    I2CInit1();     // BME280
    TimerPwmInit(); // Grow light PWM
    BH1750_Init();

    UartPuts("STM32 Sensor Node Started\r\n");

    while(1)
    {
        // LIGHT SENSOR
        light_intensity = BH1750_ReadLux();
        led_status = GrowLightControl();

        // SOIL MOISTURE & PUMP
        pump_status = SoilMoistureControl(&soil_moisture);

        // MQ135 GAS
        MQ135_GetValue(&mq135_adc);

        // TEMPERATURE & FAN
        fan_status = FanControl(&temperature, &humidity);

        // SEND CSV LINE OVER UART
        sprintf(uart_buf,
            "%u,%u,%u,%u,%u,%.2f,%.2f,%u\r\n",
            light_intensity,
            led_status,
            soil_moisture,
			pump_status,
            mq135_adc,
            temperature,
            humidity,
            fan_status
        );

        UartPuts(uart_buf);
        DelayMs(LOOP_DELAY_MS);
    }
}
