/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */

/*

PA2 (USART2_TX)   ----->     RX
PA3 (USART2_RX)   <-----     TX
GND               --------    GND
3.3V (optional)   ----->     VCC (only if TTL needs power)


VCC        -------->   3.3V
GND        -------->   GND
SCL        -------->   PB6  (I2C1_SCL)
SDA        -------->   PB7  (I2C1_SDA)
ADDR       -------->   GND  (Sensor address = 0x23)


 */
#include "stm32f4xx.h"   // CMSIS header for STM32F4 registers
#include "i2c.h"         // Your register-level I2C driver
#include "uart.h"        // UART driver for serial printing
#include "bh1750.h"      // BH1750 functions
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


char msg[50];

int main(void)
{
    UartInit(115200);    // Initialize UART2 @ 115200 baud
    UartPuts("UART Working...\r\n");
    I2CInit();           // Initialize I2C1 (PB6=SCL, PB7=SDA)
    BH1750_Init();       // Power ON - Reset - H-Resolution Mode

    while(1)
    {
        uint16_t lux = BH1750_ReadLux();   // Read light intensity in lux
        sprintf(msg, "Light Intensity = %u lux\r\n", lux); // Format string
        UartPuts(msg);                      // Send to UART
        DelayMs(500);                      // Read 2 times per second
    }
}
